services:
  - type: web
    name: chatbot-vectorial-db
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
